### ISSUE TITLE
Promises broken

### ISSUE THREAD

**Issue by cmloegcmluin** [bkonkle/babel-preset-es2015-loose#3]
The commit made yesterday (751f709cacd877474c6aaffa4f900e4507323c6f, merging in 4f6df9f4611a2e9630efcec0ce478ec89b96a2a7) somehow breaks Promises. 

We get:
SyntaxError: Unexpected identifier
when attempting to use Promise.all

We are locked down on version 6.1.2 for the time being, then.

**Comment by bkonkle** [comment]
This is definitely unusual. I'm about to head to lunch, but afterwards I'll check to see if there's anything wrong with the way I'm enabling loose mode. If not, we might need to post this as a bug to ESLint, since the real action is happening in the transform plugin. I'll let you know!

**Comment by bkonkle** [comment]
I'm not going to have time to check into this like I thought I would, and I know the problem isn't in this package itself. Before that merge this wasn't actually enabling loose mode like I thought it was - so all of the transformers were in standards compliant mode before. I'd recommend the following troubleshooting path:
- Determine which transformer is actually causing the issue. Disable loose mode for all of them, and enable each one in isolation to see which one is breaking promises for you.
- Set up a quick example project on Github that will easily demonstrate the issue. The Babel team will really appreciate an easy way to reproduce.
- Open a ticket on the Babel issue tracker here: https://phabricator.babeljs.io/

As you'll see from the issue tracker, they're pretty busy at the moment. If you can continue on in standards compliant mode and you're getting decent performance, then great! You can wait for them to resolve the issue. If you need loose mode right now, your best bet is likely to downgrade to Babel 5 until the issue is fixed.

**Comment by ambyjkl** [comment]
This seems to still be an issue unfortunately
