### ISSUE TITLE
peerDependencies and NPM3

### ISSUE THREAD

**Issue by dwightjack** [bkonkle/babel-preset-es2015-loose#8]
Hi,

with npm v3+ the package `babel-preset-es2015` listed in `peerDependencies` doesn't get installed resulting in an error.

**Comment by bkonkle** [comment]
Thanks for letting me know! I added instructions to install `babel-preset-es2015` to the README. The idea is that `babel-preset-es2015-loose` will always be up to date because it will always use the version of `babel-preset-2015` the user has installed. If you don't want to update to the latest Babel release - you don't have to. Just pin `babel-preset-2015` to the version you need.
